//! Rust backend — ports [`WriteParser.hs`](../../../pappy/pappy/WriteParser.hs). Emits a crate-ready
//! module: preamble from the grammar, [`Derivs`](crate::pappy::parser::Derivs) with `pos` + remaining
//! `text` and a Haskell-style [`Derivs::dv_char`](crate::pappy::parser::Derivs), plus per–non-terminal
//! parsers. **Supported today:** `()` rules as literal strings ([`emit_simple_unit_char_seq`]),
//! `RulePrim` **forwarding** when the callee type matches ([`forward_prim_supported`]),
//! and `()` **`RuleAlt`** of literal, unit-NT, and supported **`()`** **`RuleSeq`** branches ([`emit_unit_alt`]). **`()` `RuleSeq`** mixing
//! literals, **`RulePrim`**, PEG **`&`** ([`followed_by`](crate::pappy::parser::followed_by)) / **`!`**
//! ([`not_followed_by`](crate::pappy::parser::not_followed_by)) on literals or unit NTs
//! is handled by [`emit_unit_rule_seq`]. Postfix
//! **`?`** on literals, unit NTs, or parenthesized supported **`()`** **`RuleSeq`** ([`emit_unit_optional`] / [`opt_ignore`]) is supported for `()`.
//! Postfix **`?`** on **`String`** literals, **`String`** NTs, or supported **`String` `RuleSeq`** uses [`opt_string_default`](crate::pappy::parser::opt_string_default).
//! Pure **literal** rules typed as **`String`** use [`string_value`](crate::pappy::parser::string_value);
//! **`String` `RuleAlt`** (literals, `String` NTs, and supported **`String` `RuleSeq`** branches) uses nested **`choice`** like [`emit_unit_alt`].
//! **`String` `RuleSeq`** of merged literals plus **`String`** `RulePrim` segments, with optional PEG
//! **`&`** / **`!`** on literals or **`()`** / **`String`** NTs (zero-width; no concat), uses
//! [`emit_string_rule_seq`] — Haskell action text is not translated yet.
//! **`()` `RuleStar` / `RulePlus`** over a non-empty literal or unit **`RulePrim`** use [`many`](crate::pappy::parser::many) /
//! [`many1`](crate::pappy::parser::many1) (empty literal repetition is not supported — would not terminate).
//! After **reduce**, **`[()]`** / **`{[()]}`** / **`[String]`** / **`{[String]}`** list nonterminals use the same **`StarRule` / `PlusRule`** shape; **`String`** elements use **`string_value`** or **`String`** **`RulePrim`**.
//! Other shapes are **stubs** until full `prule` / `tie2level` codegen exists.

use std::collections::HashSet;

use super::ast::{Grammar, Identifier, Match, Nonterminal, Producer, Rule};
use super::error::PappycError;

pub fn write_parser_rust(memos: &[Identifier], g: &Grammar) -> Result<String, PappycError> {
    let dv = locase(&g.grammar_name);
    let derivs = upcase(&g.grammar_name);

    let mut out = String::new();
    out.push_str("//! Generated by pappyc (Rust backend) — do not edit.\n");
    out.push_str("//!\n");
    out.push_str("//! Translate semantic `{ ... }` blocks in the `.pappy` source from Haskell to Rust.\n\n");

    out.push_str("#![allow(dead_code)]\n");
    out.push_str("#![allow(unused_imports)]\n");
    out.push_str("use crate::pappy::basic::{join_errors, msg_error, null_error, PResult};\n");
    out.push_str("use crate::pappy::parser::{choice, followed_by, many, many1, map, not_followed_by, opt_ignore, opt_string_default, string_, string_value, Parser};\n");
    out.push_str("use crate::pappy::pos::{next_pos, Pos};\n\n");

    out.push_str(&g.grammar_raw_code);
    out.push_str("\n\n");

    out.push_str(&format!(
        "/// Packrat derivative cell for grammar `{parsername}`.\n",
        parsername = g.grammar_name
    ));
    out.push_str(&format!("#[derive(Clone)]\npub struct {derivs} {{\n"));
    out.push_str(&format!("    pub {dv}_pos: Pos,\n"));
    out.push_str("    /// Remaining input (suffix). Matches Haskell `grammarDerivs pos text` carrying `text`.\n");
    out.push_str(&format!("    pub {dv}_text: String,\n"));
    out.push_str("}\n\n");

    out.push_str(&format!(
        "impl crate::pappy::parser::Derivs for {derivs} {{\n"
    ));
    out.push_str(&format!("    fn dv_pos(&self) -> Pos {{ self.{dv}_pos.clone() }}\n"));
    out.push_str(&format!(
        "    fn dv_char(&self) -> PResult<Self, char> {{\n        match self.{dv}_text.chars().next() {{\n            None => PResult::NoParse(msg_error(self.{dv}_pos.clone(), \"end of input\")),\n            Some(c) => {{\n                let rest = self.{dv}_text[c.len_utf8()..].to_string();\n                let next_pos = next_pos(&self.{dv}_pos, c);\n                PResult::Parsed {{\n                    value: c,\n                    rest: {dv}_derivs(next_pos, rest),\n                    err: null_error(self.{dv}_pos.clone()),\n                }}\n            }}\n        }}\n    }}\n"
    ));
    out.push_str("}\n\n");

    out.push_str(&format!(
        "pub fn {dv}_parse(name: &str, text: &str) -> {derivs} {{\n    {dv}_derivs(Pos {{ file: name.to_string(), line: 1, col: 1 }}, text.to_string())\n}}\n\n"
    ));

    out.push_str(&format!(
        "fn {dv}_derivs(pos: Pos, text: String) -> {derivs} {{\n    {derivs} {{ {dv}_pos: pos, {dv}_text: text }}\n}}\n\n"
    ));

    let emit_nts = emit_nt_names(memos, &g.grammar_tops, &g.grammar_nonterminals);
    out.push_str("// Per–non-terminal parsers (memo ∪ `top` ∪ `RulePrim` closure). Unsupported shapes are stubs.\n");
    for (nt_name, typ, rule) in &g.grammar_nonterminals {
        if !emit_nts.contains(nt_name) {
            continue;
        }
        let fname = format!("{}_parse_{}", dv, locase(nt_name));
        let rt = rust_type(typ);
        out.push_str(&format!(
            "#[allow(clippy::unused_unit)]\nfn {fname}(d: &{derivs}) -> PResult<{derivs}, {rt}> {{\n",
        ));
        if simple_unit_char_seq_supported(typ, rule) {
            out.push_str(&emit_simple_unit_char_seq(&dv, typ, rule));
        } else if simple_string_literal_supported(typ, rule) {
            out.push_str(&emit_string_literal(rule));
        } else if let Some(target) = forward_prim_supported(rule, typ, &g.grammar_nonterminals) {
            out.push_str(&emit_forward_prim(&dv, target));
        } else if simple_unit_opt_rule_supported(typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_unit_optional(
                &dv,
                &derivs,
                rule,
                &g.grammar_nonterminals,
            ));
        } else if simple_string_opt_rule_supported(typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_string_optional(
                &dv,
                &derivs,
                rule,
                &g.grammar_nonterminals,
            ));
        } else if simple_unit_alt_supported(typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_unit_alt(&dv, &derivs, rule, &g.grammar_nonterminals));
        } else if simple_string_alt_supported(typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_string_alt(
                &dv,
                &derivs,
                rule,
                &g.grammar_nonterminals,
            ));
        } else if simple_string_rule_seq_supported(typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_string_rule_seq(&dv, &derivs, rule));
        } else if simple_unit_rule_seq_supported(typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_unit_rule_seq(&dv, &derivs, rule));
        } else if simple_reduced_star_list_supported(nt_name, typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_reduced_star_list(
                &dv,
                &derivs,
                nt_name,
                rule,
                &g.grammar_nonterminals,
            ));
        } else if simple_reduced_plus_list_supported(nt_name, typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_reduced_plus_list(
                &dv,
                &derivs,
                nt_name,
                rule,
                &g.grammar_nonterminals,
            ));
        } else if simple_reduced_star_string_list_supported(nt_name, typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_reduced_star_string_list(
                &dv,
                &derivs,
                nt_name,
                rule,
                &g.grammar_nonterminals,
            ));
        } else if simple_reduced_plus_string_list_supported(nt_name, typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_reduced_plus_string_list(
                &dv,
                &derivs,
                nt_name,
                rule,
                &g.grammar_nonterminals,
            ));
        } else if let Some(callee) = simple_unit_discard_list_prim_supported(typ, rule, &g.grammar_nonterminals)
        {
            out.push_str(&emit_unit_discard_list_prim(&dv, &derivs, callee));
        } else if simple_unit_star_supported(typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_unit_star(&dv, &derivs, rule, &g.grammar_nonterminals));
        } else if simple_unit_plus_supported(typ, rule, &g.grammar_nonterminals) {
            out.push_str(&emit_unit_plus(&dv, &derivs, rule, &g.grammar_nonterminals));
        } else {
            out.push_str(&emit_rule_stub(&dv, rule));
        }
        out.push_str("}\n\n");
    }

    Ok(out)
}

/// Nonterminals that get a `fn {grammar}_parse_{nt}`: memo ∪ `top`, extended by **transitive
/// `RulePrim` dependencies** so `main = leaf` emits `*_parse_leaf` as well.
fn emit_nt_names(
    memos: &[Identifier],
    tops: &[Identifier],
    nts: &[Nonterminal],
) -> HashSet<String> {
    let defined: HashSet<String> = nts.iter().map(|(n, _, _)| n.clone()).collect();
    let mut set: HashSet<String> = HashSet::new();
    for m in memos {
        set.insert(m.clone());
    }
    for t in tops {
        set.insert(t.clone());
    }
    let mut changed = true;
    while changed {
        changed = false;
        let names: Vec<String> = set.iter().cloned().collect();
        for name in names {
            let Some((_, _, rule)) = nts.iter().find(|(n, _, _)| n == &name) else {
                continue;
            };
            for p in collect_prim_refs(rule) {
                if defined.contains(&p) && set.insert(p) {
                    changed = true;
                }
            }
        }
    }
    let mut out = HashSet::new();
    for (n, _, _) in nts {
        if set.contains(n) {
            out.insert(n.clone());
        }
    }
    out
}

fn collect_prim_refs(rule: &Rule) -> Vec<String> {
    match rule {
        Rule::RulePrim(n) => vec![n.clone()],
        Rule::RuleSeq(ms, _) => ms
            .iter()
            .flat_map(|m| match m {
                Match::MatchAnon(r) => collect_prim_refs(r),
                Match::MatchName(r, _) => collect_prim_refs(r),
                Match::MatchPat(r, _) => collect_prim_refs(r),
                Match::MatchString(r, _) => collect_prim_refs(r),
                Match::MatchAnd(r) => collect_prim_refs(r),
                Match::MatchNot(r) => collect_prim_refs(r),
                Match::MatchPred(_) => vec![],
            })
            .collect(),
        Rule::RuleAlt(rs) => rs.iter().flat_map(collect_prim_refs).collect(),
        Rule::RuleOpt(r) => collect_prim_refs(r),
        Rule::RuleStar(r) | Rule::RulePlus(r) => collect_prim_refs(r),
        Rule::RuleError(r, _) => collect_prim_refs(r),
        Rule::RuleExpect(r, _) => collect_prim_refs(r),
        Rule::RuleSwitchChar(crs, d) => {
            let mut v: Vec<_> = crs
                .iter()
                .flat_map(|(_, r)| collect_prim_refs(r))
                .collect();
            if let Some(r) = d {
                v.extend(collect_prim_refs(r));
            }
            v
        }
        Rule::RuleSwitchString(_, crs, d) => {
            let mut v: Vec<_> = crs
                .iter()
                .flat_map(|(_, r)| collect_prim_refs(r))
                .collect();
            if let Some(r) = d {
                v.extend(collect_prim_refs(r));
            }
            v
        }
        Rule::RuleChar(_) | Rule::RulePos | Rule::RuleString(_) => vec![],
    }
}

/// `foo = bar` / `foo :: T = bar` with identical result types — delegate to `bar`'s parser.
/// After reduce, a single NT reference is often `RuleSeq([MatchAnon(RulePrim(..))], …)` (producer ignored).
fn forward_prim_supported<'a>(
    rule: &'a Rule,
    typ: &str,
    nts: &[Nonterminal],
) -> Option<&'a str> {
    let target = rule_as_forward_prim_name(rule)?;
    let want = typ.trim();
    let (_, t2, _) = nts.iter().find(|(n, _, _)| n == target)?;
    (t2.trim() == want).then_some(target)
}

fn rule_as_forward_prim_name(rule: &Rule) -> Option<&str> {
    match rule {
        Rule::RulePrim(n) => Some(n.as_str()),
        Rule::RuleSeq(ms, _) if ms.len() == 1 => match &ms[0] {
            Match::MatchAnon(Rule::RulePrim(n)) => Some(n.as_str()),
            _ => None,
        },
        _ => None,
    }
}

fn emit_forward_prim(dv: &str, target_nt: &str) -> String {
    let callee = format!("{}_parse_{}", dv, locase(target_nt));
    format!("    {callee}(d)\n")
}

/// Postfix `?` on a literal or unit NT: top-level [`Rule::RuleOpt`], or one match in `RuleSeq` with
/// `-> …` (any producer; ignored for Rust emission) ([`unwrap_unit_opt_rule`]).
fn unwrap_unit_opt_rule(rule: &Rule) -> Option<&Rule> {
    match rule {
        Rule::RuleOpt(inner) => Some(inner.as_ref()),
        Rule::RuleSeq(ms, p)
            if ms.len() == 1
                && (matches!(p, Producer::ProdCode(_)) || matches!(p, Producer::ProdName(_))) =>
        {
            match &ms[0] {
                Match::MatchAnon(Rule::RuleOpt(i)) => Some(i.as_ref()),
                Match::MatchName(Rule::RuleOpt(i), _) => Some(i.as_ref()),
                _ => None,
            }
        }
        _ => None,
    }
}

fn unit_opt_inner_supported(inner: &Rule, nts: &[Nonterminal]) -> bool {
    extract_unit_char_seq(inner).is_some()
        || forward_prim_supported(inner, "()", nts).is_some()
        || simple_unit_rule_seq_supported("()", inner, nts)
}

fn simple_unit_opt_rule_supported(typ: &str, rule: &Rule, nts: &[Nonterminal]) -> bool {
    if typ.trim() != "()" {
        return false;
    }
    let Some(inner) = unwrap_unit_opt_rule(rule) else {
        return false;
    };
    unit_opt_inner_supported(inner, nts)
}

fn emit_unit_optional(dv: &str, derivs: &str, rule: &Rule, nts: &[Nonterminal]) -> String {
    let inner = unwrap_unit_opt_rule(rule).expect("emit_unit_optional: not optional");
    let expr = if extract_unit_char_seq(inner).is_some() {
        let s: String = extract_unit_char_seq(inner).unwrap().iter().collect();
        format!("opt_ignore(string_({:?}))", s)
    } else if let Some(t) = forward_prim_supported(inner, "()", nts) {
        let callee = format!("{}_parse_{}", dv, locase(t));
        format!("opt_ignore(Parser::new(|dvs: {derivs}| {callee}(&dvs)))")
    } else if simple_unit_rule_seq_supported("()", inner, nts) {
        let body = emit_unit_rule_seq_body(dv, derivs, inner, "dvs");
        format!("opt_ignore(Parser::new(|dvs: {derivs}| {{\n{body}}}))")
    } else {
        unreachable!("emit_unit_optional: inner not emittable")
    };
    format!("    {expr}.parse(d.clone())\n")
}

/// `?` on a literal or `String` NT: top-level [`Rule::RuleOpt`], or one match in `RuleSeq` with `->`
/// (including `-> { … }`; producer ignored — result is `""` when absent).
fn unwrap_string_opt_rule(rule: &Rule) -> Option<&Rule> {
    match rule {
        Rule::RuleOpt(inner) => Some(inner.as_ref()),
        Rule::RuleSeq(ms, p)
            if ms.len() == 1
                && (matches!(p, Producer::ProdCode(_)) || matches!(p, Producer::ProdName(_))) =>
        {
            match &ms[0] {
                Match::MatchAnon(Rule::RuleOpt(i)) | Match::MatchName(Rule::RuleOpt(i), _) => {
                    Some(i.as_ref())
                }
                _ => None,
            }
        }
        _ => None,
    }
}

fn string_opt_inner_supported(inner: &Rule, nts: &[Nonterminal]) -> bool {
    extract_unit_char_seq(inner).is_some()
        || forward_prim_supported(inner, "String", nts).is_some()
        || simple_string_rule_seq_supported("String", inner, nts)
}

fn simple_string_opt_rule_supported(typ: &str, rule: &Rule, nts: &[Nonterminal]) -> bool {
    if typ.trim() != "String" {
        return false;
    }
    let Some(inner) = unwrap_string_opt_rule(rule) else {
        return false;
    };
    string_opt_inner_supported(inner, nts)
}

fn emit_string_optional(dv: &str, derivs: &str, rule: &Rule, nts: &[Nonterminal]) -> String {
    let inner = unwrap_string_opt_rule(rule).expect("emit_string_optional: not optional");
    let expr = if extract_unit_char_seq(inner).is_some() {
        let s: String = extract_unit_char_seq(inner).unwrap().iter().collect();
        format!("opt_string_default(string_value({:?}))", s)
    } else if let Some(t) = forward_prim_supported(inner, "String", nts) {
        let callee = format!("{}_parse_{}", dv, locase(t));
        format!("opt_string_default(Parser::new(|dvs: {derivs}| {callee}(&dvs)))")
    } else if simple_string_rule_seq_supported("String", inner, nts) {
        let body = emit_string_rule_seq_body(dv, derivs, inner, "dvs");
        format!("opt_string_default(Parser::new(|dvs: {derivs}| {{\n{body}}}))")
    } else {
        unreachable!("emit_string_optional: inner not emittable")
    };
    format!("    {expr}.parse(d.clone())\n")
}

fn simple_unit_alt_supported(typ: &str, rule: &Rule, nts: &[Nonterminal]) -> bool {
    if typ.trim() != "()" {
        return false;
    }
    let Rule::RuleAlt(alts) = rule else {
        return false;
    };
    !alts.is_empty()
        && alts.iter().all(|a| {
            extract_unit_char_seq(a).is_some()
                || forward_prim_supported(a, "()", nts).is_some()
                || simple_unit_rule_seq_supported("()", a, nts)
        })
}

/// `()` alternation: each branch is a literal run or a single unit **`RulePrim`** (incl. reduced `RuleSeq`).
#[derive(Debug)]
enum UnitSeqSeg {
    Lit(String),
    Prim(String),
    /// `!literal` — must not match here (no input consumed).
    NotLit(String),
    /// `!nt` — callee is **`()`** or **`String`** (value discarded for lookahead).
    NotPrim(String),
    /// `&literal` — must match here (no input consumed).
    AndLit(String),
    /// `&nt` — callee is **`()`** or **`String`**.
    AndPrim(String),
}

/// `()` sequence of literal chunks and `RulePrim` calls; producer is ignored (Haskell/Rust actions not emitted).
fn simple_unit_rule_seq_supported(typ: &str, rule: &Rule, nts: &[Nonterminal]) -> bool {
    if typ.trim() != "()" {
        return false;
    }
    let Rule::RuleSeq(ms, _) = rule else {
        return false;
    };
    let Some(segs) = unit_rule_seq_segments(ms) else {
        return false;
    };
    for seg in &segs {
        match seg {
            UnitSeqSeg::Prim(n) => {
                if !prim_has_unit_type(n, nts) {
                    return false;
                }
            }
            UnitSeqSeg::NotPrim(n) | UnitSeqSeg::AndPrim(n) => {
                if !prim_has_unit_or_string_type(n, nts) {
                    return false;
                }
            }
            UnitSeqSeg::Lit(_) | UnitSeqSeg::NotLit(_) | UnitSeqSeg::AndLit(_) => {}
        }
    }
    true
}

fn prim_has_unit_or_string_type(nt: &str, nts: &[Nonterminal]) -> bool {
    prim_has_unit_type(nt, nts) || prim_has_string_type(nt, nts)
}

fn prim_has_unit_type(nt: &str, nts: &[Nonterminal]) -> bool {
    nts
        .iter()
        .find(|(n, _, _)| n == nt)
        .is_some_and(|(_, t, _)| t.trim() == "()")
}

fn prim_has_string_type(nt: &str, nts: &[Nonterminal]) -> bool {
    nts
        .iter()
        .find(|(n, _, _)| n == nt)
        .is_some_and(|(_, t, _)| t.trim() == "String")
}

/// `"a" b` / `a b` / `&peek "hi"` with `String` result: literals plus `String` NTs; producer ignored (concat).
/// At least one **literal** or **`String`** **`RulePrim`** must contribute to the result (lookahead-only
/// sequences are rejected).
fn simple_string_rule_seq_supported(typ: &str, rule: &Rule, nts: &[Nonterminal]) -> bool {
    if typ.trim() != "String" {
        return false;
    }
    let Rule::RuleSeq(ms, _) = rule else {
        return false;
    };
    let Some(segs) = unit_rule_seq_segments(ms) else {
        return false;
    };
    if segs.iter().all(|s| matches!(s, UnitSeqSeg::Lit(_))) {
        return false;
    }
    let has_concat_source = segs
        .iter()
        .any(|s| matches!(s, UnitSeqSeg::Lit(_)))
        || segs.iter().any(|s| matches!(s, UnitSeqSeg::Prim(_)));
    if !has_concat_source {
        return false;
    }
    for seg in &segs {
        match seg {
            UnitSeqSeg::Prim(n) => {
                if !prim_has_string_type(n, nts) {
                    return false;
                }
            }
            UnitSeqSeg::NotPrim(n) | UnitSeqSeg::AndPrim(n) => {
                if !prim_has_unit_or_string_type(n, nts) {
                    return false;
                }
            }
            UnitSeqSeg::Lit(_) | UnitSeqSeg::NotLit(_) | UnitSeqSeg::AndLit(_) => {}
        }
    }
    true
}

/// `d_bind` is the **`Derivs`** parameter name (`d` in top-level `fn *_parse_*`, `dvs` inside nested `Parser::new`).
fn emit_string_rule_seq_body(dv: &str, derivs: &str, rule: &Rule, d_bind: &str) -> String {
    let Rule::RuleSeq(ms, _) = rule else {
        unreachable!();
    };
    let segs = unit_rule_seq_segments(ms).expect("emit_string_rule_seq: segments");
    let mut out = String::new();
    out.push_str(&format!("        let mut cur = {d_bind}.clone();\n"));
    out.push_str(&format!(
        "        let mut acc_err = null_error({d_bind}.{dv}_pos.clone());\n"
    ));
    out.push_str("        let mut acc_s = String::new();\n");
    for seg in segs {
        match seg {
            UnitSeqSeg::Lit(s) => {
                out.push_str(&format!(
                    "        match string_({:?}).parse(cur) {{\n",
                    s
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => {\n");
                out.push_str("                acc_err = join_errors(acc_err, err);\n");
                out.push_str(&format!("                acc_s.push_str({:?});\n", s));
                out.push_str("                cur = rest;\n");
                out.push_str("            }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::Prim(n) => {
                let callee = format!("{}_parse_{}", dv, locase(&n));
                out.push_str(&format!("        match {callee}(&cur) {{\n"));
                out.push_str("            PResult::Parsed { value, rest, err } => {\n");
                out.push_str("                acc_err = join_errors(acc_err, err);\n");
                out.push_str("                acc_s.push_str(&value);\n");
                out.push_str("                cur = rest;\n");
                out.push_str("            }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::NotLit(s) => {
                out.push_str(&format!(
                    "        match not_followed_by(string_({:?})).parse(cur) {{\n",
                    s
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => {\n");
                out.push_str("                acc_err = join_errors(acc_err, err);\n");
                out.push_str("                cur = rest;\n");
                out.push_str("            }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::NotPrim(n) => {
                let callee = format!("{}_parse_{}", dv, locase(&n));
                out.push_str(&format!(
                    "        match not_followed_by(Parser::new(|dvs: {derivs}| {callee}(&dvs))).parse(cur) {{\n"
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => {\n");
                out.push_str("                acc_err = join_errors(acc_err, err);\n");
                out.push_str("                cur = rest;\n");
                out.push_str("            }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::AndLit(s) => {
                out.push_str(&format!(
                    "        match followed_by(string_({:?})).parse(cur) {{\n",
                    s
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => {\n");
                out.push_str("                acc_err = join_errors(acc_err, err);\n");
                out.push_str("                cur = rest;\n");
                out.push_str("            }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::AndPrim(n) => {
                let callee = format!("{}_parse_{}", dv, locase(&n));
                out.push_str(&format!(
                    "        match followed_by(Parser::new(|dvs: {derivs}| {callee}(&dvs))).parse(cur) {{\n"
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => {\n");
                out.push_str("                acc_err = join_errors(acc_err, err);\n");
                out.push_str("                cur = rest;\n");
                out.push_str("            }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
        }
    }
    out.push_str("        PResult::Parsed { value: acc_s, rest: cur, err: acc_err }\n");
    out
}

fn emit_string_rule_seq(dv: &str, derivs: &str, rule: &Rule) -> String {
    let body = emit_string_rule_seq_body(dv, derivs, rule, "d");
    format!("    {{\n{body}    }}\n")
}

/// Split `RuleSeq` matches into merged literal strings and primitive NT references.
fn unit_rule_seq_segments(ms: &[Match]) -> Option<Vec<UnitSeqSeg>> {
    let mut segs: Vec<UnitSeqSeg> = Vec::new();
    let mut lit_buf: Vec<char> = Vec::new();
    let flush = |buf: &mut Vec<char>, segs: &mut Vec<UnitSeqSeg>| {
        if !buf.is_empty() {
            segs.push(UnitSeqSeg::Lit(buf.iter().collect()));
            buf.clear();
        }
    };
    for m in ms {
        match m {
            Match::MatchAnon(Rule::RulePrim(n)) | Match::MatchName(Rule::RulePrim(n), _) => {
                flush(&mut lit_buf, &mut segs);
                segs.push(UnitSeqSeg::Prim(n.clone()));
            }
            Match::MatchNot(r) => {
                flush(&mut lit_buf, &mut segs);
                if let Some(chars) = extract_unit_char_seq(r) {
                    if chars.is_empty() {
                        return None;
                    }
                    segs.push(UnitSeqSeg::NotLit(chars.iter().collect()));
                } else if let Rule::RulePrim(n) = r {
                    segs.push(UnitSeqSeg::NotPrim(n.clone()));
                } else {
                    return None;
                }
            }
            Match::MatchAnd(r) => {
                flush(&mut lit_buf, &mut segs);
                if let Some(chars) = extract_unit_char_seq(r) {
                    if chars.is_empty() {
                        return None;
                    }
                    segs.push(UnitSeqSeg::AndLit(chars.iter().collect()));
                } else if let Rule::RulePrim(n) = r {
                    segs.push(UnitSeqSeg::AndPrim(n.clone()));
                } else {
                    return None;
                }
            }
            m => {
                let chars = match_to_literal_chars(m)?;
                lit_buf.extend(chars);
            }
        }
    }
    flush(&mut lit_buf, &mut segs);
    Some(segs)
}

fn match_to_literal_chars(m: &Match) -> Option<Vec<char>> {
    match m {
        Match::MatchAnon(r) => extract_unit_char_seq(r),
        Match::MatchName(r, _) => extract_unit_char_seq(r),
        _ => None,
    }
}

fn emit_unit_rule_seq_body(dv: &str, derivs: &str, rule: &Rule, d_bind: &str) -> String {
    let Rule::RuleSeq(ms, _) = rule else {
        unreachable!();
    };
    let segs = unit_rule_seq_segments(ms).expect("checked");
    let mut out = String::new();
    out.push_str(&format!("        let mut cur = {d_bind}.clone();\n"));
    out.push_str(&format!(
        "        let mut acc_err = null_error({d_bind}.{dv}_pos.clone());\n"
    ));
    for seg in segs {
        match seg {
            UnitSeqSeg::Lit(s) => {
                out.push_str(&format!(
                    "        match string_({:?}).parse(cur) {{\n",
                    s
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => { acc_err = join_errors(acc_err, err); cur = rest; }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::Prim(n) => {
                let callee = format!("{}_parse_{}", dv, locase(&n));
                out.push_str(&format!("        match {callee}(&cur) {{\n"));
                out.push_str("            PResult::Parsed { rest, err, .. } => { acc_err = join_errors(acc_err, err); cur = rest; }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::NotLit(s) => {
                out.push_str(&format!(
                    "        match not_followed_by(string_({:?})).parse(cur) {{\n",
                    s
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => { acc_err = join_errors(acc_err, err); cur = rest; }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::NotPrim(n) => {
                let callee = format!("{}_parse_{}", dv, locase(&n));
                out.push_str(&format!(
                    "        match not_followed_by(Parser::new(|dvs: {derivs}| {callee}(&dvs))).parse(cur) {{\n"
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => { acc_err = join_errors(acc_err, err); cur = rest; }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::AndLit(s) => {
                out.push_str(&format!(
                    "        match followed_by(string_({:?})).parse(cur) {{\n",
                    s
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => { acc_err = join_errors(acc_err, err); cur = rest; }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
            UnitSeqSeg::AndPrim(n) => {
                let callee = format!("{}_parse_{}", dv, locase(&n));
                out.push_str(&format!(
                    "        match followed_by(Parser::new(|dvs: {derivs}| {callee}(&dvs))).parse(cur) {{\n"
                ));
                out.push_str("            PResult::Parsed { rest, err, .. } => { acc_err = join_errors(acc_err, err); cur = rest; }\n");
                out.push_str("            PResult::NoParse(e) => return PResult::NoParse(join_errors(acc_err, e)),\n");
                out.push_str("        }\n");
            }
        }
    }
    out.push_str("        PResult::Parsed { value: (), rest: cur, err: acc_err }\n");
    out
}

fn emit_unit_rule_seq(dv: &str, derivs: &str, rule: &Rule) -> String {
    let body = emit_unit_rule_seq_body(dv, derivs, rule, "d");
    format!("    {{\n{body}    }}\n")
}

/// Reduce expands `*` / `+` to `StarRuleN` / `PlusRuleN` list nonterminals (`reduce_grammar.rs`).
fn match_reduced_star_list_rule<'a>(nt_name: &str, rule: &'a Rule) -> Option<&'a Rule> {
    let Rule::RuleAlt(alts) = rule else {
        return None;
    };
    if alts.len() != 2 {
        return None;
    }
    let Rule::RuleSeq(ms0, p0) = &alts[0] else {
        return None;
    };
    let Rule::RuleSeq(ms1, p1) = &alts[1] else {
        return None;
    };
    if !matches!(p0, Producer::ProdCode(c) if c.trim() == "v : vs") {
        return None;
    }
    if !matches!(p1, Producer::ProdCode(c) if c.trim() == "[]") {
        return None;
    }
    if !ms1.is_empty() || ms0.len() != 2 {
        return None;
    }
    let Match::MatchName(r1, v) = &ms0[0] else {
        return None;
    };
    let Match::MatchName(Rule::RulePrim(rec), vs) = &ms0[1] else {
        return None;
    };
    if v != "v" || vs != "vs" || rec != nt_name {
        return None;
    }
    Some(r1)
}

fn match_reduced_plus_list_rule<'a>(nt_name: &str, rule: &'a Rule) -> Option<&'a Rule> {
    let Rule::RuleAlt(alts) = rule else {
        return None;
    };
    if alts.len() != 2 {
        return None;
    }
    let Rule::RuleSeq(ms0, p0) = &alts[0] else {
        return None;
    };
    let Rule::RuleSeq(ms1, p1) = &alts[1] else {
        return None;
    };
    if !matches!(p0, Producer::ProdCode(c) if c.trim() == "v : vs") {
        return None;
    }
    if !matches!(p1, Producer::ProdCode(c) if c.trim() == "[v]") {
        return None;
    }
    if ms0.len() != 2 || ms1.len() != 1 {
        return None;
    }
    let Match::MatchName(r1, v) = &ms0[0] else {
        return None;
    };
    let Match::MatchName(Rule::RulePrim(rec), vs) = &ms0[1] else {
        return None;
    };
    let Match::MatchName(_, v2) = &ms1[0] else {
        return None;
    };
    if v != "v" || vs != "vs" || v2 != "v" || rec != nt_name {
        return None;
    }
    Some(r1)
}

fn list_nt_is_unit_vec(typ: &str) -> bool {
    matches!(typ.trim(), "[()]" | "{[()]}")
}

fn list_nt_is_string_vec(typ: &str) -> bool {
    matches!(typ.trim(), "[String]" | "{[String]}")
}

fn string_repeat_inner_supported(inner: &Rule, nts: &[Nonterminal]) -> bool {
    if let Some(chars) = extract_unit_char_seq(inner) {
        !chars.is_empty()
    } else {
        forward_prim_supported(inner, "String", nts).is_some()
    }
}

fn string_repeat_inner_parser_expr(
    dv: &str,
    derivs: &str,
    inner: &Rule,
    nts: &[Nonterminal],
) -> String {
    if let Some(chars) = extract_unit_char_seq(inner) {
        let s: String = chars.iter().collect();
        format!("string_value({:?})", s)
    } else if let Some(t) = forward_prim_supported(inner, "String", nts) {
        let callee = format!("{}_parse_{}", dv, locase(t));
        format!("Parser::new(|dvs: {derivs}| {callee}(&dvs))")
    } else {
        unreachable!("string_repeat_inner_parser_expr: inner not emittable")
    }
}

fn simple_reduced_star_list_supported(
    nt_name: &str,
    typ: &str,
    rule: &Rule,
    nts: &[Nonterminal],
) -> bool {
    list_nt_is_unit_vec(typ)
        && match_reduced_star_list_rule(nt_name, rule)
            .is_some_and(|inner| unit_repeat_inner_supported(inner, nts))
}

fn simple_reduced_plus_list_supported(
    nt_name: &str,
    typ: &str,
    rule: &Rule,
    nts: &[Nonterminal],
) -> bool {
    list_nt_is_unit_vec(typ)
        && match_reduced_plus_list_rule(nt_name, rule)
            .is_some_and(|inner| unit_repeat_inner_supported(inner, nts))
}

fn simple_reduced_star_string_list_supported(
    nt_name: &str,
    typ: &str,
    rule: &Rule,
    nts: &[Nonterminal],
) -> bool {
    list_nt_is_string_vec(typ)
        && match_reduced_star_list_rule(nt_name, rule)
            .is_some_and(|inner| string_repeat_inner_supported(inner, nts))
}

fn simple_reduced_plus_string_list_supported(
    nt_name: &str,
    typ: &str,
    rule: &Rule,
    nts: &[Nonterminal],
) -> bool {
    list_nt_is_string_vec(typ)
        && match_reduced_plus_list_rule(nt_name, rule)
            .is_some_and(|inner| string_repeat_inner_supported(inner, nts))
}

fn emit_reduced_star_list(
    dv: &str,
    derivs: &str,
    nt_name: &str,
    rule: &Rule,
    nts: &[Nonterminal],
) -> String {
    let inner = match_reduced_star_list_rule(nt_name, rule).expect("emit_reduced_star_list");
    let p = unit_repeat_inner_parser_expr(dv, derivs, inner, nts);
    format!("    map(many({p}), |vs| vs).parse(d.clone())\n")
}

fn emit_reduced_plus_list(
    dv: &str,
    derivs: &str,
    nt_name: &str,
    rule: &Rule,
    nts: &[Nonterminal],
) -> String {
    let inner = match_reduced_plus_list_rule(nt_name, rule).expect("emit_reduced_plus_list");
    let p = unit_repeat_inner_parser_expr(dv, derivs, inner, nts);
    format!("    map(many1({p}), |vs| vs).parse(d.clone())\n")
}

fn emit_reduced_star_string_list(
    dv: &str,
    derivs: &str,
    nt_name: &str,
    rule: &Rule,
    nts: &[Nonterminal],
) -> String {
    let inner = match_reduced_star_list_rule(nt_name, rule).expect("emit_reduced_star_string_list");
    let p = string_repeat_inner_parser_expr(dv, derivs, inner, nts);
    format!("    map(many({p}), |vs| vs).parse(d.clone())\n")
}

fn emit_reduced_plus_string_list(
    dv: &str,
    derivs: &str,
    nt_name: &str,
    rule: &Rule,
    nts: &[Nonterminal],
) -> String {
    let inner = match_reduced_plus_list_rule(nt_name, rule).expect("emit_reduced_plus_string_list");
    let p = string_repeat_inner_parser_expr(dv, derivs, inner, nts);
    format!("    map(many1({p}), |vs| vs).parse(d.clone())\n")
}

/// `() = StarRuleN -> ()` after reduce: parse list then discard.
fn simple_unit_discard_list_prim_supported<'a>(
    typ: &str,
    rule: &'a Rule,
    nts: &'a [Nonterminal],
) -> Option<&'a str> {
    if typ.trim() != "()" {
        return None;
    }
    let Rule::RuleSeq(ms, _) = rule else {
        return None;
    };
    if ms.len() != 1 {
        return None;
    }
    let Match::MatchAnon(Rule::RulePrim(callee)) = &ms[0] else {
        return None;
    };
    let (_, t, _) = nts.iter().find(|(n, _, _)| n == callee)?;
    list_nt_is_discardable_vec(t).then_some(callee.as_str())
}

fn list_nt_is_discardable_vec(typ: &str) -> bool {
    list_nt_is_unit_vec(typ) || list_nt_is_string_vec(typ)
}

fn emit_unit_discard_list_prim(dv: &str, derivs: &str, callee: &str) -> String {
    let f = format!("{}_parse_{}", dv, locase(callee));
    format!("    map(Parser::new(|dvs: {derivs}| {f}(&dvs)), |_| ()).parse(d.clone())\n")
}

/// `*` / `+` over a non-empty literal or unit `RulePrim` (`()`). Empty `string_("")` would loop forever in `many`.
fn unit_repeat_inner_supported(inner: &Rule, nts: &[Nonterminal]) -> bool {
    if let Some(chars) = extract_unit_char_seq(inner) {
        !chars.is_empty()
    } else {
        forward_prim_supported(inner, "()", nts).is_some()
    }
}

/// Top-level [`Rule::RuleStar`] or `"a"* -> ()` as [`RuleSeq`] with one [`MatchAnon`](Match::MatchAnon)([`RuleStar`]).
fn unwrap_unit_star_inner(rule: &Rule) -> Option<&Rule> {
    match rule {
        Rule::RuleStar(inner) => Some(inner.as_ref()),
        Rule::RuleSeq(ms, p)
            if ms.len() == 1
                && (matches!(p, Producer::ProdCode(_)) || matches!(p, Producer::ProdName(_))) =>
        {
            match &ms[0] {
                Match::MatchAnon(Rule::RuleStar(i)) | Match::MatchName(Rule::RuleStar(i), _) => {
                    Some(i.as_ref())
                }
                _ => None,
            }
        }
        _ => None,
    }
}

/// Top-level [`Rule::RulePlus`] or `"a"+ -> ()` as [`RuleSeq`] with one match wrapping [`RulePlus`].
fn unwrap_unit_plus_inner(rule: &Rule) -> Option<&Rule> {
    match rule {
        Rule::RulePlus(inner) => Some(inner.as_ref()),
        Rule::RuleSeq(ms, p)
            if ms.len() == 1
                && (matches!(p, Producer::ProdCode(_)) || matches!(p, Producer::ProdName(_))) =>
        {
            match &ms[0] {
                Match::MatchAnon(Rule::RulePlus(i)) | Match::MatchName(Rule::RulePlus(i), _) => {
                    Some(i.as_ref())
                }
                _ => None,
            }
        }
        _ => None,
    }
}

fn simple_unit_star_supported(typ: &str, rule: &Rule, nts: &[Nonterminal]) -> bool {
    typ.trim() == "()"
        && unwrap_unit_star_inner(rule).is_some_and(|inner| unit_repeat_inner_supported(inner, nts))
}

fn simple_unit_plus_supported(typ: &str, rule: &Rule, nts: &[Nonterminal]) -> bool {
    typ.trim() == "()"
        && unwrap_unit_plus_inner(rule).is_some_and(|inner| unit_repeat_inner_supported(inner, nts))
}

fn unit_repeat_inner_parser_expr(
    dv: &str,
    derivs: &str,
    inner: &Rule,
    nts: &[Nonterminal],
) -> String {
    if let Some(chars) = extract_unit_char_seq(inner) {
        let s: String = chars.iter().collect();
        format!("string_({:?})", s)
    } else if let Some(t) = forward_prim_supported(inner, "()", nts) {
        let callee = format!("{}_parse_{}", dv, locase(t));
        format!("Parser::new(|dvs: {derivs}| {callee}(&dvs))")
    } else {
        unreachable!("unit_repeat_inner_parser_expr: inner not emittable")
    }
}

fn emit_unit_star(dv: &str, derivs: &str, rule: &Rule, nts: &[Nonterminal]) -> String {
    let inner = unwrap_unit_star_inner(rule).expect("emit_unit_star");
    let p = unit_repeat_inner_parser_expr(dv, derivs, inner, nts);
    format!("    map(many({p}), |_| ()).parse(d.clone())\n")
}

fn emit_unit_plus(dv: &str, derivs: &str, rule: &Rule, nts: &[Nonterminal]) -> String {
    let inner = unwrap_unit_plus_inner(rule).expect("emit_unit_plus");
    let p = unit_repeat_inner_parser_expr(dv, derivs, inner, nts);
    format!("    map(many1({p}), |_| ()).parse(d.clone())\n")
}

fn emit_unit_alt(dv: &str, derivs: &str, rule: &Rule, nts: &[Nonterminal]) -> String {
    let Rule::RuleAlt(alts) = rule else {
        unreachable!("emit_unit_alt: not RuleAlt");
    };
    let mut exprs: Vec<String> = Vec::new();
    for a in alts {
        if extract_unit_char_seq(a).is_some() {
            let s: String = extract_unit_char_seq(a).unwrap().iter().collect();
            exprs.push(format!("string_({:?})", s));
        } else if let Some(t) = forward_prim_supported(a, "()", nts) {
            let callee = format!("{}_parse_{}", dv, locase(t));
            exprs.push(format!("Parser::new(|dvs: {derivs}| {callee}(&dvs))"));
        } else if simple_unit_rule_seq_supported("()", a, nts) {
            let body = emit_unit_rule_seq_body(dv, derivs, a, "dvs");
            exprs.push(format!(
                "Parser::new(|dvs: {derivs}| {{\n{body}}})"
            ));
        } else {
            unreachable!("emit_unit_alt: branch not emittable");
        }
    }
    let expr = fold_choice_parsers(&exprs);
    format!("    {expr}.parse(d.clone())\n")
}

fn simple_string_alt_supported(typ: &str, rule: &Rule, nts: &[Nonterminal]) -> bool {
    if typ.trim() != "String" {
        return false;
    }
    let Rule::RuleAlt(alts) = rule else {
        return false;
    };
    !alts.is_empty()
        && alts.iter().all(|a| {
            extract_unit_char_seq(a).is_some()
                || forward_prim_supported(a, "String", nts).is_some()
                || simple_string_rule_seq_supported("String", a, nts)
        })
}

fn emit_string_alt(dv: &str, derivs: &str, rule: &Rule, nts: &[Nonterminal]) -> String {
    let Rule::RuleAlt(alts) = rule else {
        unreachable!("emit_string_alt: not RuleAlt");
    };
    let mut exprs: Vec<String> = Vec::new();
    for a in alts {
        if extract_unit_char_seq(a).is_some() {
            let s: String = extract_unit_char_seq(a).unwrap().iter().collect();
            exprs.push(format!("string_value({:?})", s));
        } else if let Some(t) = forward_prim_supported(a, "String", nts) {
            let callee = format!("{}_parse_{}", dv, locase(t));
            exprs.push(format!("Parser::new(|dvs: {derivs}| {callee}(&dvs))"));
        } else if simple_string_rule_seq_supported("String", a, nts) {
            let body = emit_string_rule_seq_body(dv, derivs, a, "dvs");
            exprs.push(format!(
                "Parser::new(|dvs: {derivs}| {{\n{body}}})"
            ));
        } else {
            unreachable!("emit_string_alt: branch not emittable");
        }
    }
    let expr = fold_choice_parsers(&exprs);
    format!("    {expr}.parse(d.clone())\n")
}

/// Nested `choice(p, choice(…))` for homogeneous `Parser<D, V>` expression strings.
fn fold_choice_parsers(exprs: &[String]) -> String {
    debug_assert!(!exprs.is_empty());
    if exprs.len() == 1 {
        return exprs[0].clone();
    }
    format!(
        "choice({}, {})",
        exprs[0],
        fold_choice_parsers(&exprs[1..])
    )
}

fn simple_unit_char_seq_supported(typ: &str, rule: &Rule) -> bool {
    typ.trim() == "()" && extract_unit_char_seq(rule).is_some()
}

fn simple_string_literal_supported(typ: &str, rule: &Rule) -> bool {
    typ.trim() == "String" && extract_unit_char_seq(rule).is_some()
}

fn emit_string_literal(rule: &Rule) -> String {
    let chars = extract_unit_char_seq(rule).expect("emit_string_literal: not a literal");
    let s: String = chars.iter().collect();
    format!("    string_value({:?}).parse(d.clone())\n", s)
}

/// Literal character run after reduce. `RuleString "a"` can become a nested `RuleSeq` inside
/// `MatchAnon` (see `reduce_grammar` / `RuleString`), so we recurse through `MatchAnon(RuleSeq(…))`.
fn extract_unit_char_seq(rule: &Rule) -> Option<Vec<char>> {
    match rule {
        Rule::RuleSeq(ms, _) => chars_from_literal_matches(ms),
        Rule::RuleChar(c) => Some(vec![*c]),
        _ => None,
    }
}

fn chars_from_literal_matches(ms: &[Match]) -> Option<Vec<char>> {
    let mut out = Vec::new();
    for m in ms {
        match m {
            Match::MatchAnon(Rule::RuleChar(c)) => out.push(*c),
            Match::MatchAnon(Rule::RuleSeq(inner, _)) => {
                out.extend(chars_from_literal_matches(inner)?);
            }
            _ => return None,
        }
    }
    Some(out)
}

/// Emit a `()` parser for a literal character run (after reduce: `RuleSeq` of `RuleChar` or one `RuleChar`).
fn emit_simple_unit_char_seq(_dv: &str, typ: &str, rule: &Rule) -> String {
    debug_assert!(simple_unit_char_seq_supported(typ, rule));
    let chars = extract_unit_char_seq(rule).unwrap_or_default();
    let s: String = chars.iter().collect();
    format!("    string_({:?}).parse(d.clone())\n", s)
}

fn rust_type(t: &str) -> String {
    let t = t.trim();
    if t == "()" {
        "()".into()
    } else if let Some(inner) = t.strip_prefix('{').and_then(|s| s.strip_suffix('}')) {
        rust_type(inner)
    } else if let Some(inner) = t.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
        format!("Vec<{}>", rust_type(inner))
    } else {
        t.to_string()
    }
}

fn emit_rule_stub(dv: &str, rule: &Rule) -> String {
    format!(
        "    let _ = {rule:?};\n    PResult::NoParse(null_error(d.{dv}_pos))\n",
    )
}

fn upcase(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

fn locase(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}
